export class SlingshotModal {
    
  districtList = [
    { name: 'Ahmednagar', isRegistered: false },
    { name: 'Akola', isRegistered: false },
    { name: 'Amravati', isRegistered: false },
    { name: 'Aurangabad', isRegistered: false },
    { name: 'Bhandara', isRegistered: false },
    { name: 'Buldhana', isRegistered: false },
    { name: 'Chandrapur', isRegistered: false },
    { name: 'Dhule', isRegistered: false },
    { name: 'Gadchiroli', isRegistered: false },
    { name: 'Gondia', isRegistered: false },
    { name: 'Hingoli', isRegistered: false },
    { name: 'Jalgaon', isRegistered: false },
    { name: 'Jalna', isRegistered: false },
    { name: 'Kolhapur', isRegistered: false },
    { name: 'Latur', isRegistered: false },
    { name: 'Mumbai', isRegistered: false },
    { name: 'Nagpur', isRegistered: false },
    { name: 'Nanded', isRegistered: false },
    { name: 'Nandurbar', isRegistered: false },
    { name: 'Nashik', isRegistered: false },
    { name: 'Osmanabad', isRegistered: false },
    { name: 'Palghar', isRegistered: false },
    { name: 'Parbhani', isRegistered: false },
    { name: 'Pune', isRegistered: false },
    { name: 'Raigad', isRegistered: false },
    { name: 'Alibag', isRegistered: false },
    { name: 'Ratnagiri', isRegistered: false },
    { name: 'Sangli', isRegistered: false },
    { name: 'Satara', isRegistered: false },
    { name: 'Sindhudurg', isRegistered: false },
    { name: 'Oros', isRegistered: false },
    { name: 'Solapur', isRegistered: false },
    { name: 'Thane', isRegistered: false },
    { name: 'Wardha', isRegistered: false },
    { name: 'Washim', isRegistered: false },
    { name: 'Yavatmal', isRegistered: false }
  ];
}
